config/routes.rb
Rails.application.routes.draw do
  get 'employees/add'
  get 'employees/delete'
  get 'jobs/index'
  get 'jobs/show'
  get 'jobs/add'
  get 'jobs/edit'
  devise_for :users
  get 'scheduler/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "scheduler#index"

  get "employees/add", to: "employees#add", as: "add_new_employee"
  post "employee", to: "employees#create", as: "create_employee"
  delete "employees/:id", to: "employees#delete", as: "delete_employee"

  get "jobs/add", to: "jobs#add", as: "add_job"
  delete "jobs/:id", to: "jobs#delete", as: "remove_job"
  get "jobs/:id", to: "jobs#show", as: "show_job"
  post "jobs", to: "jobs#create", as: "create_job"
  patch "jobs/update_job", to: "jobs#update", as: "update_job"
  patch "jobs/add_employee", to: "jobs#add_employee", as: "add_employee"
  patch "jobs/mark_job_completed", to: "jobs#mark_job_completed", as: "mark_job_completed"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone_number, presence: true
    has_many :employee_jobs
    has_many :jobs, through: :employee_jobs

    def name
        return "#{first_name} #{last_name}"
    end
end

app/models/employee_job.rb
class EmployeeJob < ApplicationRecord
  belongs_to :job
  belongs_to :employee
end

app/models/job.rb
class Job < ApplicationRecord
    validates :name, presence: true
    validates :location, presence: true
    validates :start_date, presence: true
    validates :days_to_complete, presence: true
    belongs_to :user
    has_many :employee_jobs
    has_many :employees, through: :employee_jobs

    def remove_employees
        employees.each { |employee|
            employee.job = nil
            employee.save
        }
    end

    def end_date
        return start_date + days_to_complete.days
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def add
    @employee = Employee.new
  end

  def create
    employee = Employee.new
    employee.first_name = params[:employee][:first_name]
    employee.last_name = params[:employee][:last_name]
    employee.phone_number = params[:employee][:phone_number]

    if employee.save
      redirect_to root_path
    else
      flash[:alert] = employee.errors.full_messages[0]
      redirect_to add_new_employee_path
    end
  end

  def delete
    Employee.find(params[:id])&.destroy
    redirect_to root_path
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def show
    @job = Job.find(params[:id])
    
    # Need to modify to include employees where their current job's end date is before this job's start date
    @available_employees = []
    Employee.all.order(first_name: :asc).each { |emp|
      available = true

      emp.jobs.each { |job|
        if @job.start_date <= job.end_date && @job.end_date >= job.start_date
          available = false
          break
        end
      }
      
      @available_employees << emp if available
    }
  end

  def delete
    job = Job.find(params[:id])
    job.remove_employees
    job.destroy
    redirect_to root_path
  end

  def update
    job = Job.find(params[:job][:job_id])
    job.start_date = Date.new params[:job]["start_date(1i)"].to_i, params[:job]["start_date(2i)"].to_i, params[:job]["start_date(3i)"].to_i
    job.days_to_complete = params[:job][:days_to_complete]
    job.save
    redirect_to show_job_path(job.id)
  end

  def add_employee
    job = Job.find(params[:job][:job_id])
    employee = Employee.find(params[:job][:employees])
    employee.jobs << job
    employee.save
    redirect_to show_job_path(job.id)
  end

  def mark_job_completed
    job = Job.find(params[:job][:job_id])
    job.complete = params[:job][:complete]
    job.employees.clear
    if job.save
      redirect_to root_path
    else
      flash[:alert] = job.errors.full_messages[0]
      redirect_to root_path
    end
  end

  def add
    @job = Job.new
  end

  def create
    job = Job.new
    job.user = current_user
    job.name = params[:job][:name]
    job.location = params[:job][:location]
    job.days_to_complete = params[:job][:days_to_complete]
    job.complete = false
    job.start_date = Date.new params[:job]["start_date(1i)"].to_i, params[:job]["start_date(2i)"].to_i, params[:job]["start_date(3i)"].to_i

    if job.save
      redirect_to root_path
    else
      flash[:alert] = job.errors.full_messages[0]
      redirect_to add_job_path
    end
  end

  def edit
  end
end

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController
  before_action :check_login_status
  
  def index
    @jobs = Job.where(user: current_user).order(complete: :asc).order(start_date: :asc).order(days_to_complete: :asc)
    @employees = Employee.all.order(first_name: :asc).order(last_name: :asc)
  end

  def check_login_status
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/scheduler_helper.rb
module SchedulerHelper
end

app/views/employees/add.html.erb
<%= form_for @employee, url: create_employee_path do |form| %>
    <div>
        <%= form.label :first_name %>
        <%= form.text_field :first_name, required: "required" %>
    </div>
    <div>
        <%= form.label :last_name %>
        <%= form.text_field :last_name, required: "required" %>
    </div>
    <div>
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, required: "required" %>
    </div>
    <%= form.submit "Submit" %>
<% end %>

app/views/jobs/add.html.erb
<%= form_for @job, url: create_job_path do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name, required: "required" %>
    </div>
    <div>
        <%= form.label :location %>
        <%= form.text_field :location, required: "required" %>
    </div>
    <div>
        <%= form.label :start_date %>
        <%= form.date_select :start_date %>
    </div>
    <div>
        <%= form.label :days_to_complete %>
        <%= form.number_field :days_to_complete, step: 1, min: 1, value: 1, required: "required" %>
    </div>
    <%= form.submit "Submit" %>
<% end %>

app/views/jobs/show.html.erb
<%= link_to "Home", root_path %>
<h1><%= @job.name %></h1>
<p><%= @job.location %></p>

<%= form_for @job, url: mark_job_completed_path do |form| %>
    <%= form.hidden_field "job_id", value: @job.id %>
    <%= form.label :complete %>
    <%= form.check_box :complete, onclick:"this.form.submit()" %>
<% end %>

<div id="details">
    <p>Start Date: <%= @job.start_date %></p>
    <p>Days to Complete: <%= @job.days_to_complete %></p>
    <div>
        <% @job.employees.each do |employee| %>
            <p><%= employee.name %></p>
        <% end %>
    </div>
    <% if !@job.complete %>
        <div id="buttons">
                <button onclick="edit()">Edit</button>
                <button onclick="add_employee()">Add Employee</button>
        </div>
    <% end %>
</div>

<div id="edit-form" style="display: none">
    <%= form_for @job, url: update_job_path do |form| %>
        <%= form.hidden_field "job_id", value: @job.id %>
        <div>
            <%= form.label :start_date %>
            <%= form.date_select :start_date, value: @job.start_date %>
        </div>
        <div>
            <%= form.label :days_to_complete %>
            <%= form.number_field :days_to_complete, step: 1, min: 1, value: @job.days_to_complete %>
        </div>
        <%= form.submit "Submit" %>
        <%= link_to "Cancel", :back %>
    <% end %>
</div>

<div id="add-employee" style="display: none">
    <div>
        <%= form_for @job, url: add_employee_path do |form| %>
            <%= form.hidden_field "job_id", value: @job.id %>
            <%= form.label :employees %>
            <%= form.collection_select :employees, @available_employees, :id, :name %>
            <%= form.submit "Submit" %>
            <%= link_to "Cancel", :back %>
        <% end %>
    </div>
</div>


<%= button_to "Delete", remove_job_path(@job.id), method: :delete %>

<script>
    function edit() {
        document.getElementById("details").style.display = "none";
        document.getElementById("edit-form").style.display = "block";
    }

    function add_employee() {
        document.getElementById("buttons").style.display = "none";
        document.getElementById("add-employee").style.display = "block";
    }

    function cancel() {
        document.getElementById("buttons").style.display = "block";
        document.getElementById("edit-form").style.display = "none";
        document.getElementById("add-employee").style.display = "none";
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Job Scheduler</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/scheduler/_employees.html.erb
<%= button_to "Add a new employee", add_new_employee_path, method: :get %>

<table>
    <tr>
        <th>Employee</th>
        <th>Contact</th>
        <th>Current Job</th>
    </tr>
    <% @employees.each do |employee| %>
        <tr>
            <td><%= employee.name %></td>
            <td><%= employee.phone_number %></td>
            <td>
                <% employee.jobs.each do |job| %>
                    <p><%= link_to job.name, show_job_path(job.id) %> - <%= job.start_date + (job.days_to_complete + 1).days %></p>
                <% end %>
            </td>
            <td><%= button_to "Remove", delete_employee_path(employee.id), method: :delete %></td>
        </tr>
    <% end %>
</table>

app/views/scheduler/_joblist.html.erb
<%= button_to "Add a new job", add_job_path, method: :get %>

<table>
    <tr>
        <th>Job</th>
        <th>Location</th>
        <th>Start Date</th>
        <th>Days to Complete</th>
        <th>End Date</th>
        <th>Complete?</th>
        <th>Employees Assigned</th>
    </tr>
    <% @jobs.each do |job| %>
        <tr>
            <td><%= link_to job.name, show_job_path(job.id) %></td>
            <td><%= job.location %></td>
            <td><%= job.start_date %></td>
            <td><%= job.days_to_complete %></td>
            <td><%= job.start_date + job.days_to_complete.days %></td>
            <% if job.complete %>
                <td>&#9745;</td>
            <% else %>
                <td>&#9744;</td>
            <% end %>
            <td>
                <% job.employees.each do |employee| %>
                    <p><%= employee.name %></p>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>

app/views/scheduler/index.html.erb
<button onclick="view_jobs()">Jobs</button>
<button onclick="view_employees()">Employees</button>

<div id="joblist">
    <%= render "joblist" %>
</div>

<div id="employees" style="display: none">
    <%= render "employees" %>
</div>

<script>
    function view_jobs() {
        document.getElementById("employees").style.display = "none";
        document.getElementById("joblist").style.display = "block";
    }

    function view_employees() {
        document.getElementById("employees").style.display = "block";
        document.getElementById("joblist").style.display = "none";
    }
</script>